### ISSUE TITLE
502 on a particular github.com org

### ISSUE THREAD

**Issue by epijim** [r-world-devs/GitStats#225]
Seems to be an issue with one of the Roche orgs, where it doesn't work. `insightsengineering` has SAML and 2-factor enabled, but not sure that effects API calls on public info?? Not sure if related to #140 

```r
create_gitstats() %>%
  set_connection(
    api_url = "https://api.github.com",
    token = Sys.getenv("GITHUB_PAT"),
    orgs = c("insightsengineering")
  ) %>% get_repos()
```

**Comment by maciekbanas** [comment]
Thanks for the issue, I'll dive into it.

**Comment by maciekbanas** [comment]
Yes, it probably has to do with access rights and specific form of GraphQL query I used here, which starts with:

**Comment by maciekbanas** [comment]
One reasonable handling of 502 error for GraphQL would be switching to REST API Engine instead - but that would require a bigger refactor.

**Comment by maciekbanas** [comment]
@epijim do you get this error every time when you run your the above code? I sometimes get the error, and sometimes not.
![image](https://github.com/r-world-devs/GitStats/assets/74212933/55b862c7-3125-4de2-be70-1329c0f032f2)

**Comment by maciekbanas** [comment]
And here is a proposed solution in case GraphQL fails:
![image](https://github.com/r-world-devs/GitStats/assets/74212933/005a76a0-4995-49a9-b23b-dc7a75772a2d)

**Comment by maciekbanas** [comment]
This issue is similar to #143
