### ISSUE TITLE
error handling for not connected engines

### ISSUE THREAD

**Issue by Cotau** [r-world-devs/GitStats#242]
when setting up new engine with bad gateway 404 I would consider adding a flag or remove it from gitstats object as when calling methods for all engines inside gitstats object lots of errors occurs that are happening only because of connection issues and might be misleading for developers

**Comment by maciekbanas** [comment]
Thanks @Cotau for the issue - can you provide workflow that led you to that error?

**Comment by Cotau** [comment]
yes, I just followed the workflow file but I got one of the envir variable for github pat named differently and thus got the error as the key was not correct

**Comment by maciekbanas** [comment]
Do you mean `401 Unauthorized` error?
![image](https://github.com/r-world-devs/GitStats/assets/74212933/a4879d99-a248-4850-aaa4-9d3a4ec06d83)
