### ISSUE TITLE
Tests fails as I don't have "GITLAB_PAT_PUBLIC" environmental variable defined.

### ISSUE THREAD

**Issue by maciekbanas** [r-world-devs/GitStats#252]
Tests fails as I don't have "GITLAB_PAT_PUBLIC" environmental variable defined. Maybe it would be a good idea to test which access tokens user has defined (before launching other tests) and: 
* when no tokens are found print a fail message like "To test package you should have at least THIS_TOKEN and/or THAT_TOKEN defined"
* if at least one token is found run all tests while skipping those for which access token is not defined

_Originally posted by @marcinkowskak in https://github.com/r-world-devs/GitStats/issues/249#issuecomment-1632007482_

**Comment by maciekbanas** [comment]
@marcinkowskak I wonder if I should not abort every time when one of tokens is not set up - the problem is with snapshot tests - if you set up your GITLAB_PAT_PUBLIC after running tests with none, than the new snapshots with warnings will be created for the earlier skipped tests .

**Comment by marcinkowskak** [comment]
That's something I haven't thought of, you' re right. So I guess if one or more tokens are not found the tests should fail/abort with message to set up missing tokens
