### ISSUE TITLE
Create ability to provide specific list of org/repos rather than pull entire org

### ISSUE THREAD

**Issue by epijim** [r-world-devs/GitStats#330]
For the pharmaverse usecase, we want to pull only specific repos - rather than all the repos in an org.

I'm currently not sure that is possible reading the documentation. Without this feature we are pulling a lot of information not needed. e.g. there is one pharmaverse package in the org `roche/rtables`, but there are 22 repos in the org `roche` (so 21 are just noise for this use case)

**Comment by maciekbanas** [comment]
We could handle it by passing a vector of repos name to the `repos` parameter to the `set_host` function, so it could look something like this:
```
create_gitstats() %>%
  set_host(
            host = "https://api.github.com",
            orgs = "r-world-devs",
            repos = c("GitStats", "shinyCohortBuilder")
  )
```
This solution would be ok? @epijim

**Comment by maciekbanas** [comment]
Probably it should be developed together with caching repos results when pulling commits #159 
And in the whole it makes probably for milestone `2.0.0`
