### ISSUE TITLE
Reorganize `set_host()` function

### ISSUE THREAD

**Issue by maciekbanas** [r-world-devs/GitStats#373]
- State clearly what API versions are managed by GitStats
- Introduce `set_gitlab_host()` and `set_github_host()` separately

**Comment by marcinkowskak** [comment]
Allow passing to `set_host()` normal URL (e.g. github.com) instead of API URL.

**Comment by maciekbanas** [comment]
@marcinkowskak so the parameter could be named `host` instead of `api_url`
