### ISSUE TITLE
Make handling inline messages more flexible

### ISSUE THREAD

**Issue by marcinkowskak** [r-world-devs/GitStats#377]
Currently, the `verbose` parameter is being set in `set_params()` function and allows to turn on/turn off messages completely.  How about an approach where in all GitStats function there is a `verbose` parameter (default set to `TRUE`) so user can flexibly turn on and off messages while calling functions

**Comment by maciekbanas** [comment]
@marcinkowskak Thanks for the issue. Introducing `verbose` parameter to every function could be a bit hard for the time-being, as it would mean passing the parameter down from GitStats wrappers to multiple methods (private and public) in many classes. Now, this is a role of one `settings` parameter which covers the issue. I am thinking of a bit different approach with the `verbose_on()` and `verbose_off()` functions which you could put in `GitStats` pipe - this would globally switch in settings `verbose` to `TRUE`/`FALSE`.
