### ISSUE TITLE
Implement statistics to `get_repos` methods

### ISSUE THREAD

**Issue by maciekbanas** [r-world-devs/GitStats#50]
On `GitHub` refer to https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository

**Comment by maciekbanas** [comment]
Example stats: `stars`, `watchers`, `forks`, if the repo is `stale`?

**Comment by marcinkowskak** [comment]
Can we pull out info about how many `contributors` the repo have?

**Comment by marcinkowskak** [comment]
Number of issues open, in progress, closed? I could nicely show how far in development specific project is.

**Comment by maciekbanas** [comment]
Add used `languages` as a column for table. It would be good also to test `language` functionality for tests.

**Comment by maciekbanas** [comment]
After adding `contributors`/`members` stats, please refactor privates `filter_by_team()` - now they connect to the `contributors`/`member` endpoints, but after adding this stats to repos it will be superfluous.

**Comment by maciekbanas** [comment]
Disclaimer: `members` are not gitlab's equivalent of github's `contributors`. Gitlab supports endpoint `repository/contributors` and it was applied in this task.

**Comment by maciekbanas** [comment]
Developed in #92
