### ISSUE TITLE
Better clean-up for commits data

### ISSUE THREAD

**Issue by marcinkowskak** [r-world-devs/GitStats#550]
For `authors_name` clean up can we add conditions for filling NA's with `user_id` in case `author_login` is empty? 

![image](https://github.com/user-attachments/assets/2f09d4f8-31ed-41ce-b347-7ae10ec1bbbf)

**Comment by maciekbanas** [comment]
I'll try to handle it. Not that simple though, as in the example above we see `user name` in `user id`, might be as well `user login`.
