### ISSUE TITLE
Improve `plot` functions.

### ISSUE THREAD

**Issue by maciekbanas** [r-world-devs/GitStats#67]

**Comment by marcinkowskak** [comment]
I'm putting some ideas for plot improvements:

plot_commit_lines():
- [ ] legend is not printed correctly: labels show only orgs name whereas it should be 'deletions' and 'additions' 
- [ ] add option to check commit lines by projects in the organization or it's team members? So far we see only number of lines 

plot_commits():
- [ ] I would add option to plot commits by repos in the organization, then we can use e.g. week granularity

Aesthetics applicable to all plots:
- [ ] use different set of colors, e.g. see pallets defined [here](https://github.roche.com/RWDScodeshare/RocheIdentity) (it should remove warning from RColorBrewer)
- [ ] add nice looking labels to axis, if we units put them in '[ ]' 
- [ ] consider adding title to the plots 
- [ ] format hoovers nicely e.g. (Feb 6, 2023, 7) -> (Date: Feb 6 2023, \n, Number of commits: 7); maybe add some details to give more information

**Comment by maciekbanas** [comment]
Thanks for these insights Karolina @marcinkowskak - if you would like to participate in some of these improvements I would be happy!
Some of these issues will need to be covered first in others, such as adding new stats - I'll try to cover it as soon as possible.

**Comment by maciekbanas** [comment]
Improved substantially commits plot with introduction of panes and making use of ggplot2 and ggplotly, also improvements added to plot repos in #212
