### ISSUE TITLE
Set up preferences in `GitStats` object

### ISSUE THREAD

**Issue by maciekbanas** [r-world-devs/GitStats#95]
@Cotau

**Comment by maciekbanas** [comment]
Add wrapper over settings, e.g. `set_team()`, `set_organizations()`.
Referring to #6

**Comment by Cotau** [comment]
the idea is to create a method that would setup all searching parameters in one place and would check if the parameters are correct, something like this:
`  setup_preferences(orgs, org_limit = 1000, team = NULL, phrase = NULL, storage = FALSE) {
    
    #check if both team and phrase are not provided, if so then stop function with callout that only one method coul be used
    self$set_organisations(orgs, org_limit)
    self$set_team(team)
    self$set_search_phrase(phrase)
    self$set_storage(storage)
  }`
  and move all of the used methods to private to make sure this we are in full control of the arguments for searching
  also print method could be rewritten to print those preferences so they can be easily checked on the go
  
  this function could be also called at the object init to setup all the options for default, or this could be used to write and read .yaml files with predifined settings if the could grow in size in future

**Comment by maciekbanas** [comment]
@Cotau that is quite a big issue - I would leave it for another PR - are you ok with that?
